use_frameworks!

target 'ReactiveBluetoothExtensions_Example' do
  pod 'ReactiveBluetoothExtensions', :path => '../'

  target 'ReactiveBluetoothExtensions_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
